/*===========================================================================
	  C++ class	definitions	exported from UnrealScript.
	  This is automatically	generated by the tools.
	  DO NOT modify	this manually! Edit	the	corresponding .uc files	instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef PATHFINDING_API
#define PATHFINDING_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern PATHFINDING_API	FName PATHFINDING_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


// Struct FConnectToElement	is declared	in "..\PathFinding\Classes\PlacedNode.uc"
struct PATHFINDING_API FConnectToElement
{
    FName Node;
    BITFIELD jetpack:1;
    FName obstacleLabel;
};





// Class	ANoPathNodeGenerationVolume is declared in "..\PathFinding\Classes\NoPathNodeGenerationVolume.uc"
class PATHFINDING_API	ANoPathNodeGenerationVolume	: public AVolume
{
public:
	   DECLARE_CLASS(ANoPathNodeGenerationVolume,AVolume,0|CLASS_Config,PathFinding)
	   NO_DEFAULT_CONSTRUCTOR(ANoPathNodeGenerationVolume)
};

// Class	APlacedNode is declared in "..\PathFinding\Classes\PlacedNode.uc"
class PATHFINDING_API	APlacedNode	: public AActor
{
public:
    TArrayNoInit<FName> doNotConnectTo;
    BITFIELD road:1;
    TArrayNoInit<FConnectToElement> connectToData;
    BITFIELD pathNodeSnap:1;
	   DECLARE_CLASS(APlacedNode,AActor,0,PathFinding)
	   NO_DEFAULT_CONSTRUCTOR(APlacedNode)
};

// Class	AAirborneNode is declared in "..\PathFinding\Classes\AirborneNode.uc"
class PATHFINDING_API	AAirborneNode	: public APlacedNode
{
public:
	   DECLARE_CLASS(AAirborneNode,APlacedNode,0,PathFinding)
	   NO_DEFAULT_CONSTRUCTOR(AAirborneNode)
};

// Class	AIndoorNode is declared in "..\PathFinding\Classes\IndoorNode.uc"
class PATHFINDING_API	AIndoorNode	: public APlacedNode
{
public:
	   DECLARE_CLASS(AIndoorNode,APlacedNode,0,PathFinding)
	   NO_DEFAULT_CONSTRUCTOR(AIndoorNode)
};

// Class	APlacedOutdoorNode is declared in "..\PathFinding\Classes\PlacedOutdoorNode.uc"
class PATHFINDING_API	APlacedOutdoorNode	: public APlacedNode
{
public:
	   DECLARE_CLASS(APlacedOutdoorNode,APlacedNode,0,PathFinding)
	   NO_DEFAULT_CONSTRUCTOR(APlacedOutdoorNode)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack	(pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(AAirborneNode)
VERIFY_CLASS_SIZE_NODIE(AIndoorNode)
VERIFY_CLASS_SIZE_NODIE(ANoPathNodeGenerationVolume)
VERIFY_CLASS_SIZE_NODIE(APlacedNode)
VERIFY_CLASS_SIZE_NODIE(APlacedOutdoorNode)
#endif // VERIFY_CLASS_SIZES
