/*===========================================================================
	  C++ class	definitions	exported from UnrealScript.
	  This is automatically	generated by the tools.
	  DO NOT modify	this manually! Edit	the	corresponding .uc files	instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef MOJOACTIONS_API
#define MOJOACTIONS_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern MOJOACTIONS_API	FName MOJOACTIONS_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY




// Enum LookAtType is declared in "..\MojoActions\Classes\TsActionKeyframeInterpolate.uc"
enum LookAtType
{
	 LOOKAT_UseKeyframe      =0,
	 LOOKAT_Actor            =1,
	 LOOKAT_Point            =2,
	 LOOKAT_MAX              =3,
};





// Class	UTsAction is declared in "..\MojoActions\Classes\TsAction.uc"
class MOJOACTIONS_API	UTsAction	: public UTsMojoAction
{
public:
    FStringNoInit DName;
    FStringNoInit Track;
    FStringNoInit Help;
    BITFIELD FastForwardSkip:1;
    BITFIELD ModifiesLocation:1;
    BITFIELD DisableInMojo:1;
    BITFIELD UsesDuration:1;
    BITFIELD bShowSubtitles:1;
    FLOAT interpTime;
	   DECLARE_FUNCTION(execShouldShowSubtitles);
	   DECLARE_FUNCTION(exectickInterpolation);
	   DECLARE_FUNCTION(execresetInterpolation);
	   DECLARE_CLASS(UTsAction,UTsMojoAction,0|CLASS_Config,MojoActions)
	   NO_DEFAULT_CONSTRUCTOR(UTsAction)
};

// Class	UTsActionInterpolateBase is declared in "..\MojoActions\Classes\TsActionInterpolateBase.uc"
class MOJOACTIONS_API	UTsActionInterpolateBase	: public UTsAction
{
public:
    FMojoKeyframe cur_keyframe;
    FVector src_tangent;
    FVector dest_tangent;
    FVector src_position;
    FVector dest_position;
	   DECLARE_CLASS(UTsActionInterpolateBase,UTsAction,0|CLASS_Config,MojoActions)
	   NO_DEFAULT_CONSTRUCTOR(UTsActionInterpolateBase)
};

// Class	UTsActionInterpolateTo is declared in "..\MojoActions\Classes\TsActionInterpolateTo.uc"
class MOJOACTIONS_API	UTsActionInterpolateTo	: public UTsActionInterpolateBase
{
public:
    FMojoKeyframe Target;
    FLOAT duration;
    FLOAT ease_in_time;
    FLOAT ease_out_time;
    FLOAT elapsed_duration;
	   DECLARE_FUNCTION(execUpdateCurrentKeyframePos);
	   DECLARE_FUNCTION(execCalculateConstants);
	   DECLARE_CLASS(UTsActionInterpolateTo,UTsActionInterpolateBase,0|CLASS_Config,MojoActions)
	   NO_DEFAULT_CONSTRUCTOR(UTsActionInterpolateTo)
};

// Class	UTsActionKeyframeInterpolate is declared in "..\MojoActions\Classes\TsActionKeyframeInterpolate.uc"
class MOJOACTIONS_API	UTsActionKeyframeInterpolate	: public UTsActionInterpolateBase
{
public:
    FLOAT duration;
    FLOAT ease_in_time;
    FLOAT ease_out_time;
    BITFIELD snap_to_first_key:1;
    BITFIELD use_linear_rotation:1;
    TArrayNoInit<FMojoKeyframe> keys;
    BYTE look_at_type;
    FMojoKeyframe look_at_point;
    FMojoActorRef look_at_actor;
    FLOAT look_at_ease_time;
    FLOAT cur_time;
    INT cur_key;
    FLOAT src_key_distance;
    FLOAT dest_key_distance;
	   DECLARE_FUNCTION(execUpdateCurrentKeyframePos);
	   DECLARE_FUNCTION(execCalculateConstants);
	   DECLARE_CLASS(UTsActionKeyframeInterpolate,UTsActionInterpolateBase,0|CLASS_Config,MojoActions)
	   NO_DEFAULT_CONSTRUCTOR(UTsActionKeyframeInterpolate)
};

// Class	UTsActionSnapTo is declared in "..\MojoActions\Classes\TsActionSnapTo.uc"
class MOJOACTIONS_API	UTsActionSnapTo	: public UTsAction
{
public:
    FMojoKeyframe Target;
    BITFIELD reset_animation:1;
	   DECLARE_CLASS(UTsActionSnapTo,UTsAction,0|CLASS_Config,MojoActions)
	   NO_DEFAULT_CONSTRUCTOR(UTsActionSnapTo)
};

// Class	UTsCameraAction is declared in "..\MojoActions\Classes\TsCameraAction.uc"
class MOJOACTIONS_API	UTsCameraAction	: public UTsAction
{
public:
    class APlayerController* PC;
	   DECLARE_CLASS(UTsCameraAction,UTsAction,0|CLASS_Config,MojoActions)
	   NO_DEFAULT_CONSTRUCTOR(UTsCameraAction)
};

// Class	UTsPawnAction is declared in "..\MojoActions\Classes\TsPawnAction.uc"
class MOJOACTIONS_API	UTsPawnAction	: public UTsAction
{
public:
    class APawn* Pawn;
	   DECLARE_CLASS(UTsPawnAction,UTsAction,0|CLASS_Config,MojoActions)
	   NO_DEFAULT_CONSTRUCTOR(UTsPawnAction)
};

// Class	UTsActionPlayLIPSinc is declared in "..\MojoActions\Classes\TsActionPlayLIPSinc.uc"
class MOJOACTIONS_API	UTsActionPlayLIPSinc	: public UTsPawnAction
{
public:
    FStringNoInit FileName;
    FStringNoInit SectionName;
    FStringNoInit TextName;
    FStringNoInit Path;
    FName LIPSincAnimName;
    FLOAT Volume;
    FLOAT Radius;
    FLOAT Pitch;
    BITFIELD bAttenuate:1;
	   DECLARE_FUNCTION(execResumeLIPSinc);
	   DECLARE_FUNCTION(execStopLIPSinc);
	   DECLARE_FUNCTION(execPauseLIPSinc);
	   DECLARE_CLASS(UTsActionPlayLIPSinc,UTsPawnAction,0|CLASS_Config,MojoActions)
	virtual void PrecacheSound(AActor* actor);
};

#endif

AUTOGENERATE_FUNCTION(UTsAction,-1,execShouldShowSubtitles);
AUTOGENERATE_FUNCTION(UTsAction,-1,exectickInterpolation);
AUTOGENERATE_FUNCTION(UTsAction,-1,execresetInterpolation);
AUTOGENERATE_FUNCTION(UTsActionInterpolateTo,-1,execUpdateCurrentKeyframePos);
AUTOGENERATE_FUNCTION(UTsActionInterpolateTo,-1,execCalculateConstants);
AUTOGENERATE_FUNCTION(UTsActionKeyframeInterpolate,-1,execUpdateCurrentKeyframePos);
AUTOGENERATE_FUNCTION(UTsActionKeyframeInterpolate,-1,execCalculateConstants);
AUTOGENERATE_FUNCTION(UTsActionPlayLIPSinc,-1,execResumeLIPSinc);
AUTOGENERATE_FUNCTION(UTsActionPlayLIPSinc,-1,execStopLIPSinc);
AUTOGENERATE_FUNCTION(UTsActionPlayLIPSinc,-1,execPauseLIPSinc);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack	(pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UTsAction)
VERIFY_CLASS_SIZE_NODIE(UTsActionInterpolateBase)
VERIFY_CLASS_SIZE_NODIE(UTsActionInterpolateTo)
VERIFY_CLASS_SIZE_NODIE(UTsActionKeyframeInterpolate)
VERIFY_CLASS_SIZE_NODIE(UTsActionPlayLIPSinc)
VERIFY_CLASS_SIZE_NODIE(UTsActionSnapTo)
VERIFY_CLASS_SIZE_NODIE(UTsCameraAction)
VERIFY_CLASS_SIZE_NODIE(UTsPawnAction)
#endif // VERIFY_CLASS_SIZES
