/*===========================================================================
	  C++ class	definitions	exported from UnrealScript.
	  This is automatically	generated by the tools.
	  DO NOT modify	this manually! Edit	the	corresponding .uc files	instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef MOVEMENT_API
#define MOVEMENT_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern MOVEMENT_API	FName MOVEMENT_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY




// Class	ABoundaryVolume is declared in "..\Movement\Classes\BoundaryVolume.uc"
class MOVEMENT_API	ABoundaryVolume	: public AVolume
{
public:
    BITFIELD Active:1;
    FLOAT DampingScale;
    FLOAT FrictionScale;
    BITFIELD LocalActive:1;
	   DECLARE_FUNCTION(execRegisterBoundary);
	   DECLARE_CLASS(ABoundaryVolume,AVolume,0|CLASS_Config,Movement)
	virtual bool HavokInitActor();
	virtual void HavokQuitActor();
};

// Class	AElevatorVolume is declared in "..\Movement\Classes\ElevatorVolume.uc"
class MOVEMENT_API	AElevatorVolume	: public APhysicsVolume
{
public:
    BITFIELD Active:1;
	   DECLARE_CLASS(AElevatorVolume,APhysicsVolume,0|CLASS_Config,Movement)
	   NO_DEFAULT_CONSTRUCTOR(AElevatorVolume)
};

// Class	AZeroGravityVolume is declared in "..\Movement\Classes\ZeroGravityVolume.uc"
class MOVEMENT_API	AZeroGravityVolume	: public APhysicsVolume
{
public:
	   DECLARE_CLASS(AZeroGravityVolume,APhysicsVolume,0|CLASS_Config,Movement)
	   NO_DEFAULT_CONSTRUCTOR(AZeroGravityVolume)
};

#endif

AUTOGENERATE_FUNCTION(ABoundaryVolume,-1,execRegisterBoundary);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack	(pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(ABoundaryVolume)
VERIFY_CLASS_SIZE_NODIE(AElevatorVolume)
VERIFY_CLASS_SIZE_NODIE(AZeroGravityVolume)
#endif // VERIFY_CLASS_SIZES
